### ISSUE TITLE
Lines should not snap to connectors so eagerly.

### ISSUE THREAD

**Issue by qwertie** [cliftonm/FlowSharp#32]
I was drawing the diagram you can see on this screenshot:

![](http://i.imgur.com/ui4BIfU.png)

The vertical lines are impossible to place after adding the text boxes ("Target", "Args[0]", etc.) because the vertical lines want very much to snap to the vertical edges of the (borderless) text boxes instead of to the outer box. It's probably best if

- Vertical lines do not snap to horizontal connectors and vice-versa
- Corner connectors should probably not exist on borderless text boxes
- Lines do not snap to connectors unless the user is dragging the end of the line (i.e. doing a resize, not a move).

The exception in the screen shot is unrelated but caused me to lose some work, since clicking Continue seems to make the same exception again. I don't know what I did to cause it but here's the stack trace:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Pen.get_Width()
   at FlowSharpLib.VerticalLine.get_UpdateRectangle()
   at FlowSharpLib.GraphicElement.OnScreen()
   at FlowSharpLib.BaseController.MoveElement(GraphicElement el, Point delta)
   at FlowSharpLib.Line.MoveElementOrAnchor(GripType gt, Point delta)
   at FlowSharpLib.CanvasController.<>c__DisplayClass8_0.<DragSelectedElements>b__0(Connection c)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FlowSharpLib.CanvasController.DragSelectedElements(Point delta)
   at FlowSharpLib.MouseController.DragShapes()
   at FlowSharpLib.MouseController.<InitializeBehavior>b__66_21()
   at FlowSharpLib.MouseController.<>c.<HandleEvent>b__67_1(MouseRouter r)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FlowSharpLib.MouseController.HandleEvent(MouseAction action)
   at FlowSharpLib.MouseController.<HookMouseEvents>b__64_2(Object sndr, MouseEventArgs args)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by qwertie** [comment]
It's also frustrating trying to avoid an unwanted connection, because let's say I move a line one pixel to the left and it decides to snap to something 10 pixels to the left. Then I have to move the mouse not ONE pixel right to correct the problem, but about 11 pixels. Combined with the other current bugs and the lack of "undo", drawing this diagram is immensely frustrating.

**Comment by cliftonm** [comment]
_Vertical lines do not snap to horizontal connectors and vice-versa
Corner connectors should probably not exist on borderless text boxes_

I don't think these two should be excluded.  Having fixed the snap behavior, I think it's much easier now to correctly snap to the desired connection point.

_Lines do not snap to connectors unless the user is dragging the end of the line (i.e. doing a resize, not a move)._

Lines are a weird situation, that I'm not actually happy with myself.  The reason that lines only snap when dragging is that, if the endpoint snaps, then the entire line would have to be moved left-right or up-down.  This may actually be acceptable behavior.  Will consider, see issue #46

_It's also frustrating trying to avoid an unwanted connection, because let's say I move a line one pixel to the left and it decides to snap to something 10 pixels to the left. Then I have to move the mouse not ONE pixel right to correct the problem, but about 11 pixels._ 

Opened and resolved as separate feature request (#45).  The quick answer is, hold down the Ctrl key while moving a connector/line, and snapping will be disabled.

The crash has been opened as issue #44.
